name: CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker containers
        run: docker compose build

      - name: Start Docker containers
        run: docker compose up -d mysql redis app

      - name: Wait for MySQL
        run: sleep 20

      - name: Run migrations
        run: docker compose exec -T app php artisan migrate --force

      - name: Run tests
        run: docker compose exec -T app php artisan test
